### PR TITLE
Switch to using generalized resources

### PR DESCRIPTION
**Pull request by nwiltsie**
# Description

This updates the pipeline to use generalized resources, as detailed in [this comment](https://github.com/uclahs-cds/pipeline-Nextflow-config/pull/73#issuecomment-2478260969).

I've updated the pipeline-Nextflow-config submodule to https://github.com/uclahs-cds/pipeline-Nextflow-config/commit/c612346db4dc50972b18ba22908c58bfd8fb391f (currently the head of https://github.com/uclahs-cds/pipeline-Nextflow-config/pull/73). That PR should be merged and the submodule updated again before _this_ PR is merged.

## Testing Results

- NFTest
  - log:      `/hot/software/pipeline/pipeline-recalibrate-BAM/Nextflow/development/unreleased/nwiltsie-generalize-resources/log-nftest-20241115T182709Z.log`
  - cases:    default set

# Checklist

- [x] I have read the [code review guidelines](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3187646/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [x] I have reviewed the [Nextflow pipeline standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3193890/Nextflow+pipeline+standardization).

- [x] The name of the branch is meaningful and well formatted following the [standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List), using \[AD\_username (or 5 letters of AD if AD is too long)]-\[brief\_description\_of\_branch\].

- [x] I have set up or verified the branch protection rule following the [github standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3190380/GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

- [x] I have added my name to the contributors listings in the ``manifest`` block in the `nextflow.config` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

- [x] I have added the changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

- [ ] I have updated the version number in the `metadata.yaml` and `manifest` block of the `nextflow.config` file following [semver](https://semver.org/), or the version number has already been updated. (*Leave it unchecked if you are unsure about new version number and discuss it with the infrastructure team in this PR.*)

- [x] I have tested the pipeline using NFTest, _or_ I have justified why I did not need to run NFTest above.

### CODE REVIEW

**Comment by yashpatel6** [comment]
@nwiltsie This should now be an identical configuration in terms of allocations and setup; the differences in the JSONs are largely due to the base allocations now being split from the retry strategy per process if you want to confirm

**Comment by nwiltsie** [comment]
> @nwiltsie This should now be an identical configuration in terms of allocations and setup; the differences in the JSONs are largely due to the base allocations now being split from the retry strategy per process if you want to confirm

Confirmed, the differences all seem structural and not quantitative. Thanks for fixing those up!

**Comment by nwiltsie** [comment]
https://github.com/uclahs-cds/pipeline-Nextflow-config/pull/73 has been merged, so I've updated the submodule to point to `main`. This is ready for review!

**Comment by yashpatel6** [comment]
I'll go over this today or tomorrow!

**Review by yashpatel6 — APPROVED** [review]
Looks good! I tweaked some of the default allocations in https://github.com/uclahs-cds/pipeline-recalibrate-BAM/pull/90/commits/9125ad6b18ebee1cf53c8f098900531052b8615c

Tested with log: `/hot/software/pipeline/pipeline-recalibrate-BAM/Nextflow/development/1.0.2/nwiltsie-generalize-resources/log-nftest-20241220T014616Z.log`

If the tweaks look good, I'm good to merge this

**Pull request merged**
